Upgrade to aws-java-sdk 1.11.507 to hopefully avoid “java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException”
https://github.com/aws/aws-sdk-java/issues/1863