Upgrade to sbt 1.1.0
This decapitalizes the label of `S3CredentialsProvider`,
otherwise sbt 1.1.0 throws an exception like the following:

    java.lang.IllegalArgumentException: requirement failed: A named attribute key must start with a lowercase letter: S3CredentialsProvider